- title: "Propuesta Técnica"
  alias: "propuesta_tecnica"
  has_intro: true
  children:
    - title: "Contexto"

    - title: "Enfoque Metodológico"

    - title: "Metodología"
      alias: "metodologia"
      has_intro: true
      children:
        - title: "ISO/IEC/IEEE 12207 — Procesos del Ciclo de Vida del Software"
          alias: "iso_12207"

        - title: "ISO/IEC 25070 — Definición de Necesidades del Usuario"
          alias: "iso_25070"

        - title: "PMBOK — Gestión del Proyecto"
          alias: "pmbok"

    - title: "Restricciones"

    - title: "Equipo"

    - title: "Gestión de Riesgos"
      alias: "riesgos"

    - title: "Plan de Trabajo"
      alias: "plan_de_trabajo"

    - title: "Aseguramiento de la Calidad del Proyecto"
      alias: "aseguramiento_calidad"

    - title: "Plan de Comunicación y Asignación de Roles (RACI)"
      alias: "plan_comunicacion_raci"
